[package]
name = "libopenssl-library"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
shared-library-builder = { git = "https://github.com/feenkcom/shared-library-builder-rs", features = ["git-location"] }
which = "4.2.2"
serde = { version = "1.0", features = [ "derive" ] }
typetag = "0.2"
cc = "1.0"
ndk-build = "0.9"